### ISSUE TITLE
missing internet connection: download auf libraries

### ISSUE THREAD

**Issue by visze** [AnacletoLAB/parSMURF#5]
Hi Ale,

the readme tells me that the following libraries are downloaded during the install process: 
- easylogging++
- jsoncons
- zlib

What happens if you are on a system without internet connection?

What happens if I preinstall the libraries? Is the installation process also downloading and installing them? And if yes, does it replace them?

Best,
Max

**Comment by AnacletoLAB** [comment]
I provided an experimental CMakeLists.txt in the experimCMakeLists folder. It is now possible to compile, but it requires a second machine (not the target machine) with internet connection.

On the second machine, clone and build the project as in the README. After that, remove the build folder (we no longer need that!) and replace the CMakeLists.txt file in the src directory with the one provided in the experimCMakeLists directory.

The resulting parSMURF folder can be copied on the target machine without the internet connection, and the software can be built as in the README, as the previous step downloaded all the need source code from third-party repositories and remove all the dependencies.
